<div style="background-color: #add8e6; padding: 10px; height: 70px; border-radius: 15px;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 50px;">
        Mohammad Idrees Bhat <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">Tech Skills Trainer | AI/ML Consultant</span> <!--- Mohammad Idrees Bhat | Tech Skills Trainer | AI/ML Consultant --->
    </div>
</div>

<!--- Mohammad Idrees Bhat | Tech Skills Trainer | AI/ML Consultant --->

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif; border-radius: 100px;">
    Feature Extraction <br>
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">  Techniques </h3>
</div

<!-- Link the Montserrat font -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">

<!-- Main div with centered content and a flexible box size, no scroll bar -->
<div style="background-color: #baf733; min-height: 100%; width: 100%; display: flex; justify-content: center; align-items: center; position: relative; padding: 20px; box-sizing: border-box; font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 20px; border-radius: 15px;">
    <div style="position: absolute; top: 10px; right: 10px; padding: 5px 10px; font-size: 14px; color: rgba(0, 0, 0, 0.05); border-radius: 10px;">Mohammad Idrees Bhat</div>
    <!-- Fill the below text with question -->
    <!-- Fill the below text with question -->
    <!-- Fill the above text with question -->
    <!-- Fill the above text with question -->
</div>

<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h3> Practical Exercise: Feature Extraction in Python
</h3> </div>

- Filter Methods (like correlation matrix):
    Identify which features are strongly correlated with the target variable.
- Wrapper Methods (like RFE):
    Use a model to help select the most important features.
- Embedded Methods (like Lasso):
    Perform feature selection as part of the model training process.

"C:\Users\devid\Desktop\datasets\Automobile_data.csv"

In [158]:
# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, chi2, RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [159]:
path = "C:\\Users\\devid\\Desktop\\datasets\\Automobile_data.csv"

# C:\Users\devid\Desktop\datasets\Automobile_data.csv"          ^
# SyntaxError: (unicode error) 'unicodeescape' codec can't decode 

df = pd.read_csv(path)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [160]:
# Handling missing values (replace '?' with NaN and drop missing values)
df.replace("?", np.nan, inplace=True)  # replaces all occurrences of "?" in the df with NaN
df.dropna(inplace=True) # removes any rows in the DataFrame that contain NaN values

# Converting necessary columns to numeric
for col in ["normalized-losses", "bore", "stroke", "horsepower", "peak-rpm", "price"]:
    df[col] = pd.to_numeric(df[col])

In [161]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**Step 2: Polynomial Features (Numerical Data)**


You can generate polynomial features for numerical columns such as curb-weight, engine-size, and horsepower to capture non-linear relationships between them.

In [162]:
from sklearn.preprocessing import PolynomialFeatures

# Select numerical columns
numerical_features = df[['curb-weight', 'engine-size', 'horsepower']]

In [163]:
# Create polynomial features (degree 2)
poly = PolynomialFeatures(degree=2)
poly_features = poly.fit_transform(numerical_features)

`PolynomialFeatures(degree=2)`:

This initializes a PolynomialFeatures object with a degree of 2.

`poly.fit_transform(numerical_features)`

learns the transformation based on the data, e.g. calculates how to create the higher-degree terms (like x^2, y^2, x*y).

After fitting, this method applies the transformation to the input data (numerical_features).

In [164]:
poly.get_feature_names_out(numerical_features.columns)

array(['1', 'curb-weight', 'engine-size', 'horsepower', 'curb-weight^2',
       'curb-weight engine-size', 'curb-weight horsepower',
       'engine-size^2', 'engine-size horsepower', 'horsepower^2'],
      dtype=object)

In [165]:


# Create a DataFrame of new features
poly_df = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(numerical_features.columns))

# Display the original and new polynomial features
print("Original Features and Polynomial Features:")
print(poly_df.head())

Original Features and Polynomial Features:
     1  curb-weight  engine-size  horsepower  curb-weight^2  \
0  1.0       2337.0        109.0       102.0      5461569.0
1  1.0       2824.0        136.0       115.0      7974976.0
2  1.0       2844.0        136.0       110.0      8088336.0
3  1.0       3086.0        131.0       140.0      9523396.0
4  1.0       2395.0        108.0       101.0      5736025.0

   curb-weight engine-size  curb-weight horsepower  engine-size^2  \
0                 254733.0                238374.0        11881.0
1                 384064.0                324760.0        18496.0
2                 386784.0                312840.0        18496.0
3                 404266.0                432040.0        17161.0
4                 258660.0                241895.0        11664.0

   engine-size horsepower  horsepower^2
0                 11118.0       10404.0
1                 15640.0       13225.0
2                 14960.0       12100.0
3                 18340.0       19600.0
4                 10908.0       10201.0

In [166]:
poly_df.head()

,1,curb-weight,engine-size,horsepower,curb-weight^2,curb-weight engine-size,curb-weight horsepower,engine-size^2,engine-size horsepower,horsepower^2
0,1.0,2337.0,109.0,102.0,5461569.0,254733.0,238374.0,11881.0,11118.0,10404.0
1,1.0,2824.0,136.0,115.0,7974976.0,384064.0,324760.0,18496.0,15640.0,13225.0
2,1.0,2844.0,136.0,110.0,8088336.0,386784.0,312840.0,18496.0,14960.0,12100.0
3,1.0,3086.0,131.0,140.0,9523396.0,404266.0,432040.0,17161.0,18340.0,19600.0
4,1.0,2395.0,108.0,101.0,5736025.0,258660.0,241895.0,11664.0,10908.0,10201.0

**Step 3: Interaction Features (Numerical Data)**

You can create interaction features by combining two numerical features, such as multiplying engine-size and curb-weight to capture interaction effects between the engine and car weight.

In [167]:
# Create interaction feature between engine-size and curb-weight
df['engine_curb_weight_interaction'] = df['engine-size'] * df['curb-weight']

# Display the new feature
print("Interaction Feature (engine-size * curb-weight):")
print(df[['engine-size', 'curb-weight', 'engine_curb_weight_interaction']].head())

Interaction Feature (engine-size * curb-weight):
    engine-size  curb-weight  engine_curb_weight_interaction
3           109         2337                          254733
4           136         2824                          384064
6           136         2844                          386784
8           131         3086                          404266
10          108         2395                          258660

In [168]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,engine_curb_weight_interaction
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950,254733
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115,5500,18,22,17450,384064
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,mpfi,3.19,3.4,8.5,110,5500,19,25,17710,386784
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,mpfi,3.13,3.4,8.3,140,5500,17,20,23875,404266
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,mpfi,3.50,2.8,8.8,101,5800,23,29,16430,258660

**Step 4: Binning (Numerical to Categorical)**

We can convert continuous numerical variables into categorical ones. For example, binning the horsepower into categories: Low, Medium, and High.

In [169]:
# Create bins for horsepower
bins = [0, 100, 150, 200]
labels = ['Low', 'Medium', 'High']

df['horsepower_binned'] = pd.cut(df['horsepower'], bins=bins, labels=labels)

`pd.cut()` is a function in pandas that is used to segment and sort data into discrete bins. It takes continuous values and categorizes them into predefined intervals (bins).

In [170]:


# Display the binned feature
print("Binned Feature (horsepower):")
print(df[['horsepower', 'horsepower_binned']].head())

Binned Feature (horsepower):
    horsepower horsepower_binned
3          102            Medium
4          115            Medium
6          110            Medium
8          140            Medium
10         101            Medium

**Step 5: Encoding Categorical Features (Textual Data)**

You can encode categorical columns like body-style using one-hot encoding or label encoding.

In [171]:
# One-hot encode the 'fuel-type' column
df_onehot = pd.get_dummies(df, columns=['body-style'], drop_first=True)
df_onehot.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,drive-wheels,engine-location,wheel-base,length,...,peak-rpm,city-mpg,highway-mpg,price,engine_curb_weight_interaction,horsepower_binned,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon
3,2,164,audi,gas,std,four,fwd,front,99.8,176.6,...,5500,24,30,13950,254733,Medium,False,False,True,False
4,2,164,audi,gas,std,four,4wd,front,99.4,176.6,...,5500,18,22,17450,384064,Medium,False,False,True,False
6,1,158,audi,gas,std,four,fwd,front,105.8,192.7,...,5500,19,25,17710,386784,Medium,False,False,True,False
8,1,158,audi,gas,turbo,four,fwd,front,105.8,192.7,...,5500,17,20,23875,404266,Medium,False,False,True,False
10,2,192,bmw,gas,std,two,rwd,front,101.2,176.8,...,5800,23,29,16430,258660,Medium,False,False,True,False

In [172]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder

# Label encode the 'body-style' column
le = LabelEncoder()
df['body-style_encoded'] = le.fit_transform(df['body-style'])

# Display the label-encoded feature
print("Label Encoded Feature (body-style):")
print(df[['body-style', 'body-style_encoded']].head())

Label Encoded Feature (body-style):
   body-style  body-style_encoded
3       sedan                   3
4       sedan                   3
6       sedan                   3
8       sedan                   3
10      sedan                   3

for `label_encoders = {}` The keys will be the column names of your DataFrame df that contain categorical data (i.e., columns of type 'object'), and the values will be the LabelEncoder objects used to encode these categorical values into numerical values.

In [173]:
# Encoding categorical columns

label_encoders = {}

for column in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,engine_curb_weight_interaction,horsepower_binned,body-style_encoded
3,2,164,0,1,0,0,3,1,0,99.8,...,3.4,10.0,102,5500,24,30,13950,254733,Medium,3
4,2,164,0,1,0,0,3,0,0,99.4,...,3.4,8.0,115,5500,18,22,17450,384064,Medium,3
6,1,158,0,1,0,0,3,1,0,105.8,...,3.4,8.5,110,5500,19,25,17710,386784,Medium,3
8,1,158,0,1,1,0,3,1,0,105.8,...,3.4,8.3,140,5500,17,20,23875,404266,Medium,3
10,2,192,1,1,0,1,3,2,0,101.2,...,2.8,8.8,101,5800,23,29,16430,258660,Medium,3

### **Step 6: Dimensionality Reduction (Optional)**

Using PCA to reduce the dimensionality of a feature set might be useful if the dataset has a lot of numerical features. For simplicity, we'll use some of the numerical features.

In [174]:
from sklearn.decomposition import PCA

In [175]:


# Select numerical features for PCA
numerical_features = df[['curb-weight', 'engine-size', 'horsepower', 'city-mpg', 'highway-mpg']]

# Apply PCA
pca = PCA(n_components=2)  # Reduce to 2 dimensions

pca_features = pca.fit_transform(numerical_features)

# Display the reduced features
print("Reduced Features using PCA:")
print(pca_features[:5])

Reduced Features using PCA:
[[-1.23989885e+02 -1.04557656e+01]
 [ 3.63886516e+02 -3.73556650e-01]
 [ 3.83534750e+02  5.90427734e+00]
 [ 6.26123462e+02 -2.34310236e+00]
 [-6.62468467e+01 -5.24056145e+00]]

The Output `(pca_features[:5])`:

- The output shows the first 5 rows of the transformed data. 
- Each row represents a car's data projected onto the 2 principal components.
- These two values represent the coordinates of each data point (car) in the new 2-dimensional space defined by the principal components.

In very simple terms, after applying PCA to your data, you transformed your original 5 features (like weight, engine size, horsepower, etc.) into just 2 new features called principal components.

Instead of thinking about 5 attributes for each car, you're now thinking about 2 combined values that capture the most important differences between the cars.

The first value in each pair tells you how the car is positioned along the first principal component (which captures the biggest difference between cars).

The second value tells you how the car is positioned along the second principal component (which captures the next biggest difference).

In [176]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,engine_curb_weight_interaction,horsepower_binned,body-style_encoded
3,2,164,0,1,0,0,3,1,0,99.8,...,3.4,10.0,102,5500,24,30,13950,254733,Medium,3
4,2,164,0,1,0,0,3,0,0,99.4,...,3.4,8.0,115,5500,18,22,17450,384064,Medium,3
6,1,158,0,1,0,0,3,1,0,105.8,...,3.4,8.5,110,5500,19,25,17710,386784,Medium,3
8,1,158,0,1,1,0,3,1,0,105.8,...,3.4,8.3,140,5500,17,20,23875,404266,Medium,3
10,2,192,1,1,0,1,3,2,0,101.2,...,2.8,8.8,101,5800,23,29,16430,258660,Medium,3

In [177]:
# Convert PCA features to a DataFrame with appropriate column names
pca_df = pd.DataFrame(pca_features, columns=['PCA1', 'PCA2'])

In [178]:
# Add the PCA features back to the original dataframe
df = pd.concat([df, pca_df], axis=1)

In [179]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,horsepower,peak-rpm,city-mpg,highway-mpg,price,engine_curb_weight_interaction,horsepower_binned,body-style_encoded,PCA1,PCA2
3,2.0,164.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,99.8,...,102.0,5500.0,24.0,30.0,13950.0,254733.0,Medium,3.0,626.123462,-2.343102
4,2.0,164.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,99.4,...,115.0,5500.0,18.0,22.0,17450.0,384064.0,Medium,3.0,-66.246847,-5.240561
6,1.0,158.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,105.8,...,110.0,5500.0,19.0,25.0,17710.0,386784.0,Medium,3.0,252.001751,-24.682154
8,1.0,158.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,105.8,...,140.0,5500.0,17.0,20.0,23875.0,404266.0,Medium,3.0,-976.362946,2.551792
10,2.0,192.0,1.0,1.0,0.0,1.0,3.0,2.0,0.0,101.2,...,101.0,5800.0,23.0,29.0,16430.0,258660.0,Medium,3.0,-553.677250,-1.428452

In [180]:
# Drop the original numerical columns to reduce complexity
df.drop(columns=['curb-weight', 'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'], inplace=True)

In [181]:
# Display the updated dataframe
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,peak-rpm,price,engine_curb_weight_interaction,horsepower_binned,body-style_encoded,PCA1,PCA2
3,2.0,164.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,99.8,...,3.19,3.4,10.0,5500.0,13950.0,254733.0,Medium,3.0,626.123462,-2.343102
4,2.0,164.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,99.4,...,3.19,3.4,8.0,5500.0,17450.0,384064.0,Medium,3.0,-66.246847,-5.240561
6,1.0,158.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,105.8,...,3.19,3.4,8.5,5500.0,17710.0,386784.0,Medium,3.0,252.001751,-24.682154
8,1.0,158.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,105.8,...,3.13,3.4,8.3,5500.0,23875.0,404266.0,Medium,3.0,-976.362946,2.551792
10,2.0,192.0,1.0,1.0,0.0,1.0,3.0,2.0,0.0,101.2,...,3.50,2.8,8.8,5800.0,16430.0,258660.0,Medium,3.0,-553.677250,-1.428452

Apply PCA again on the updated dataset (which now includes PCA1 and PCA2)

In [182]:
# Select the columns to apply PCA again (excluding non-numerical columns)
columns_for_pca = df.select_dtypes(include=['float64', 'int64']).columns

In [183]:
columns_for_pca

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'engine-type',
       'num-of-cylinders', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'peak-rpm', 'price',
       'engine_curb_weight_interaction', 'body-style_encoded', 'PCA1', 'PCA2'],
      dtype='object')

In [184]:
# Impute missing values with the median of each column
df[columns_for_pca] = df[columns_for_pca].fillna(df[columns_for_pca].median())

In [185]:
# Apply PCA again on the dataset
pca = PCA(n_components=2)  # Reduce to 2 dimensions again
pca_features = pca.fit_transform(df[columns_for_pca])

In [186]:
# Convert PCA features to a DataFrame with appropriate column names
pca_df = pd.DataFrame(pca_features, columns=['PCA1_reduced', 'PCA2_reduced'])

In [187]:
# Add the new PCA features back to the original dataframe
df = pd.concat([df, pca_df], axis=1)

In [188]:
# Drop the original columns that were used for the second PCA
df.drop(columns=columns_for_pca, inplace=True)

In [189]:
# Display the updated dataframe with reduced columns
df.head()

   horsepower_binned   PCA1_reduced  PCA2_reduced
3             Medium  107635.578437   8998.125872
4             Medium  -38145.229351   6859.421442
6             Medium  147678.148344   4589.667469
8             Medium -206336.042585   1661.805362
10            Medium -125296.282103    169.647584

Not always beneficial or useful, but now you know what to do!

<div style="background-color: lightblue; color: white; padding: 10px; text-align: center;">
    <h1>____________________         BEST OF LUCK   ...  :)        _____________________
        <!--- Mohammad Idrees Bhat | Tech Skills Trainer | AI/ML Consultant --->
</h1> </div>

<div style="background-color: #002147; color: #fff; padding: 30px; text-align: center;">
    <h1>THANK YOU!
        <!--- Mohammad Idrees Bhat | Tech Skills Trainer | AI/ML Consultant --->
</h1> </div>

<!--- Mohammad Idrees Bhat | Mohammad Idrees Bhat --->

<h2 style="background-color: #ffe4e1; color: #2f4f4f; padding: 10px; border-radius: 10px; width: 350px; text-align: center; float: right; margin: 20px 0;">
    Mohammad Idrees Bhat<br>
    <span style="font-size: 12px; color: #696969;">
        Tech Skills Trainer | AI/ML Consultant
    </span>
</h2>

<!--- Mohammad Idrees Bhat | Tech Skills Trainer | AI/ML Consultant --->